name: CI
run-name: >
  CI (${{ github.event_name }})
  ${{ github.event_name == 'pull_request' && format('PR#{0}', github.event.number) || '' }}

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  schedule:
    - cron: 0 0 * * 3

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    uses: ./.github/workflows/step_pre-commit.yaml

  tests:
    needs: [ pre-commit ]
    uses: ./.github/workflows/step_test.yaml
    with:
      mask-experimental: ${{ github.event_name == 'push' }}
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  docs:
    name: 📘 docs
    needs: [ pre-commit ]
    uses: ./.github/workflows/step_docs.yaml

  build-wheel:
    uses: ./.github/workflows/step_build-wheel.yaml
    needs: [ pre-commit ]

  pass:
    name: Pass
    needs: [ pre-commit, tests, build-wheel ]
    runs-on: ubuntu-latest
    steps:
      - uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
    if: always()
