on:
  workflow_call:

permissions:
  contents: read

jobs:
  build:
    name: 🐍 sdist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: hynek/build-and-inspect-python-package@v3.0.1
